# User config
author: "Lisandro Fern√°ndez"
tagline: "Pineapple Certfied Jekyll Theme"
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
#baseurl: "/pineapple"
#baseurl: "lifofernandez.github.io"
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

